name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
            version: "17.0"
      - name: "Build and Run"
        run: make compile-run
