name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LLVM and Clang
        run: |
            sudo apt-get update
            sudo apt-get install -y llvm clang
            sudo apt-get install -y npm
      
      - name: Install syntax-cli
        run: npm install -g syntax-cli

      - name: "Build and Run"
        run: make run
